#!/usr/bin/env python3
"""Verify mathematical expressions generated by the AI using SymPy.

Usage:
  python scripts/verify_math.py "integrate(x**2, x)" "x**3/3"
  python scripts/verify_math.py --diff "x**2" "2*x"
  python scripts/verify_math.py "integrate(sin(x), x)" "-cos(x)"
"""

from __future__ import annotations

import argparse
import sys

try:
    import sympy as sp
    HAS_SYMPY = True
except ImportError:
    HAS_SYMPY = False


def verify_integral(expr_str: str, answer_str: str) -> tuple[bool, str]:
    """Verify that differentiate(answer) == expr."""
    x = sp.Symbol("x")
    try:
        expr = sp.sympify(expr_str)
        answer = sp.sympify(answer_str)
    except (sp.SympifyError, TypeError, ValueError) as exc:
        return False, f"Parse error: {exc}"
    diff = sp.diff(answer, x)
    simplified = sp.simplify(diff - expr)
    if simplified == 0:
        return True, f"✓ {answer_str} is correct (d/dx -> {sp.pretty(diff)})"
    else:
        return False, f"✗ Incorrect. d/dx of answer = {sp.pretty(diff)}, expected {sp.pretty(expr)}"


def verify_derivative(expr_str: str, answer_str: str) -> tuple[bool, str]:
    """Verify that integrate(answer) == expr or derivative matches."""
    x = sp.Symbol("x")
    try:
        expr = sp.sympify(expr_str)
        answer = sp.sympify(answer_str)
    except (sp.SympifyError, TypeError, ValueError) as exc:
        return False, f"Parse error: {exc}"
    expr_deriv = sp.diff(expr, x)
    simplified = sp.simplify(expr_deriv - answer)
    if simplified == 0:
        return True, f"✓ {answer_str} is the derivative of {expr_str}"
    else:
        return False, f"✗ Incorrect. Derivative of {expr_str} = {sp.pretty(expr_deriv)}, not {answer_str}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verify math expressions with SymPy.")
    parser.add_argument("expr", help="Original expression (e.g. 'x**2' or 'integrate(x**2, x)')")
    parser.add_argument("answer", help="AI-generated answer to verify")
    parser.add_argument("--diff", action="store_true", help="Treat expr as the function, answer as its derivative")
    args = parser.parse_args(argv)

    if not HAS_SYMPY:
        print(
            "UNVERIFIED: SymPy is not installed, so this result was NOT checked. "
            "Do not present it as confirmed — label it 未经符号验证，置信度降低 and "
            "grade conservatively. Install with: python -m pip install sympy",
            file=sys.stderr,
        )
        return 2

    if args.diff:
        ok, msg = verify_derivative(args.expr, args.answer)
    else:
        ok, msg = verify_integral(args.expr, args.answer)

    print(msg)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
